# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X28BvNnUIGvBah4xVXN2ZwzqGN-vu-bP
"""

!pip install ultralytics

import numpy as np
import cv2
from ultralytics import YOLO

path = '/content/drive/MyDrive/854671-hd_1920_1080_25fps.mp4'#đường dẫn đến video
path_to_save_video = '/content/drive/MyDrive/out.mp4' #đường dẫn lưu video
model = YOLO('yolov8n.pt') #model yolov8n



video = cv2.VideoCapture(path)
fps = video.get(cv2.CAP_PROP_FPS) #lấy fps của video gốc
width, height = int(video.get(3)), int(video.get(4)) #lấy chiều rộng cao của video gốc
out = cv2.VideoWriter(path_to_save_video, cv2.VideoWriter_fourcc(*'mp4v'),fps ,(width, height))

while video.isOpened():
    ret, img_show = video.read() #đọc video theo frame
    if img_show is None:
        break

    pred = model(img_show, verbose= False)
    for r in pred:
        if len(pred[0]) != 0:
            xy_bboxs = r.boxes.xyxy.cpu().numpy() #bbox của object
            conf_bboxs = r.boxes.conf.cpu().numpy() #conf của các bbox
            for i in range(len(xy_bboxs)):
                xmin, ymin, xmax, ymax = int(xy_bboxs[i][0]), int(xy_bboxs[i][1]), int(xy_bboxs[i][2]), int(xy_bboxs[i][3])
                cv2.rectangle(img_show, (xmin, ymin), (xmax, ymax), (255, 0, 0), 1) #vẽ bbox
                cv2.putText(img_show, str(round(conf_bboxs[i], 2)), (xmax, ymax-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 2) #vẽ conf score
            out.write(img_show)
        else:
            out.write(img_show)
out.release()